version: '3.7'

volumes:
  myig-postgre: {}
  myig-backend-prod: {}

services:
  backend:
    container_name: myig-backend
    image: myig-backend:prod
    build:
      context: ./backend
      dockerfile: ./build/prod.Dockerfile
    volumes:
      - ./backend:/app
      - myig-backend-prod:/app/node_modules
    environment: &db_config
      - POSTGRES_HOST=${MYIG_DB_HOST}
      - POSTGRES_DB=${MYIG_DB_NAME}
      - POSTGRES_USER=${MYIG_DB_USER}
      - POSTGRES_PASSWORD=${MYIG_DB_PASSWORD}
      - POSTGRES_PORT=${MYIG_DB_PORT}
    env_file: .dev.env
    ports:
      - '8080'
    depends_on:
      - postgres
    restart: on-failure

  postgres:
    container_name: ${MYIG_DB_HOST}
    image: postgres:13-alpine
    environment: *db_config
    volumes:
      - myig-postgre:/var/lib/postgresql/data
    env_file: .dev.env
    ports:
      - '5432:${MYIG_DB_PORT}'

  frontend:
    container_name: myig-frontend
    image: myig-frontend:prod
    build:
      context: ./frontend
      dockerfile: ./build/prod.Dockerfile
    volumes:
      - ./frontend:/app
    ports:
      - '3000'
    depends_on:
      - backend
    restart: on-failure

  nginx:
    container_name: myig-nginx
    image: nginx:alpine
    ports:
      - '80:80'
    depends_on:
      - backend
      - frontend
    volumes:
      - ./dev.conf:/etc/nginx/nginx.conf:ro
