const MyTheme = {
  blockCursor: 'Editor_blockCursor',
  characterLimit: 'Editor_characterLimit',
  code: 'Editor_code',
  codeHighlight: {
    atrule: 'Editor_tokenAttr',
    attr: 'Editor_tokenAttr',
    boolean: 'Editor_tokenProperty',
    builtin: 'Editor_tokenSelector',
    cdata: 'Editor_tokenComment',
    char: 'Editor_tokenSelector',
    class: 'Editor_tokenFunction',
    'class-name': 'Editor_tokenFunction',
    comment: 'Editor_tokenComment',
    constant: 'Editor_tokenProperty',
    deleted: 'Editor_tokenProperty',
    doctype: 'Editor_tokenComment',
    entity: 'Editor_tokenOperator',
    function: 'Editor_tokenFunction',
    important: 'Editor_tokenVariable',
    inserted: 'Editor_tokenSelector',
    keyword: 'Editor_tokenAttr',
    namespace: 'Editor_tokenVariable',
    number: 'Editor_tokenProperty',
    operator: 'Editor_tokenOperator',
    prolog: 'Editor_tokenComment',
    property: 'Editor_tokenProperty',
    punctuation: 'Editor_tokenPunctuation',
    regex: 'Editor_tokenVariable',
    selector: 'Editor_tokenSelector',
    string: 'Editor_tokenSelector',
    symbol: 'Editor_tokenProperty',
    tag: 'Editor_tokenProperty',
    url: 'Editor_tokenOperator',
    variable: 'Editor_tokenVariable',
  },
  embedBlock: {
    base: 'Editor_embedBlock',
    focus: 'Editor_embedBlockFocus',
  },
  hashtag: 'Editor_hashtag',
  heading: {
    h1: 'Editor_h1',
    h2: 'Editor_h2',
    h3: 'Editor_h3',
    h4: 'Editor_h4',
    h5: 'Editor_h5',
    h6: 'Editor_h6',
  },
  image: 'editor-image',
  indent: 'Editor_indent',
  inlineImage: 'inline-editor-image',
  layoutContainer: 'Editor_layoutContaner',
  layoutItem: 'Editor_layoutItem',
  link: 'Editor_link',
  list: {
    listitem: 'Editor_listItem',
    listitemChecked: 'Editor_listItemChecked',
    listitemUnchecked: 'Editor_listItemUnchecked',
    nested: {
      listitem: 'Editor_nestedListItem',
    },
    olDepth: ['Editor_ol1', 'Editor_ol2', 'Editor_ol3', 'Editor_ol4', 'Editor_ol5'],
    ul: 'Editor_ul',
  },
  ltr: 'Editor_ltr',
  mark: 'Editor_mark',
  markOverlap: 'Editor_markOverlap',
  paragraph: 'Editor_paragraph',
  quote: 'Editor_quote',
  rtl: 'Editor_rtl',
  table: 'Editor_table',
  tableAddColumns: 'Editor_tableAddColumns',
  tableAddRows: 'Editor_tableAddRows',
  tableCell: 'Editor_tableCell',
  tableCellActionButton: 'Editor_tableCellActionButton',
  tableCellActionButtonContainer: 'Editor_tableCellActionButtonContainer',
  tableCellEditing: 'Editor_tableCellEditing',
  tableCellHeader: 'Editor_tableCellHeader',
  tableCellPrimarySelected: 'Editor_tableCellPrimarySelected',
  tableCellResizer: 'Editor_tableCellResizer',
  tableCellSelected: 'Editor_tableCellSelected',
  tableCellSortedIndicator: 'Editor_tableCellSortedIndicator',
  tableResizeRuler: 'Editor_tableCellResizeRuler',
  tableSelected: 'Editor_tableSelected',
  tableSelection: 'Editor_tableSelection',
  text: {
    bold: 'Editor_textBold',
    code: 'Editor_textCode',
    italic: 'Editor_textItalic',
    strikethrough: 'Editor_textStrikethrough',
    subscript: 'Editor_textSubscript',
    superscript: 'Editor_textSuperscript',
    underline: 'Editor_textUnderline',
    underlineStrikethrough: 'Editor_textUnderlineStrikethrough',
  },
}

export default MyTheme
