// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: function.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getLocateAt = `-- name: getLocateAt :one
SELECT  FROM set_default_locate($1, $2)
`

type getLocateAtParams struct {
	Userid   uuid.UUID
	LocateAt uuid.UUID
}

type getLocateAtRow struct {
}

func (q *Queries) getLocateAt(ctx context.Context, arg getLocateAtParams) (getLocateAtRow, error) {
	row := q.db.QueryRow(ctx, getLocateAt, arg.Userid, arg.LocateAt)
	var i getLocateAtRow
	err := row.Scan()
	return i, err
}
