// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: function.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getFolderFullPath = `-- name: GetFolderFullPath :one
SELECT FROM set_folder_full_path($1)
`

type GetFolderFullPathRow struct {
}

func (q *Queries) GetFolderFullPath(ctx context.Context, folderID uuid.UUID) (GetFolderFullPathRow, error) {
	row := q.db.QueryRow(ctx, getFolderFullPath, folderID)
	var i GetFolderFullPathRow
	err := row.Scan()
	return i, err
}
