// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package db

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type File struct {
	ID             uuid.UUID
	Name           string
	Url            *string
	CreatedAt      time.Time
	LastModifiedAt time.Time
	UserID         uuid.UUID
	LocateAt       pgtype.UUID
}

type Folder struct {
	ID             uuid.UUID
	Name           string
	LocateAt       uuid.UUID
	FullPath       interface{}
	Depth          int32
	IsDeleted      bool
	CreatedAt      time.Time
	LastModifiedAt time.Time
	UserID         uuid.UUID
}

type User struct {
	ID             uuid.UUID
	Email          string
	Password       string
	Name           string
	AvatarUrl      *string
	CreatedAt      time.Time
	LastModifiedAt time.Time
}
