// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type File struct {
	ID             uuid.UUID
	Name           string
	Url            *string
	CreatedAt      pgtype.Timestamptz
	LastModifiedAt pgtype.Timestamptz
	UserID         uuid.UUID
	LocateAt       pgtype.UUID
}

type Folder struct {
	ID             uuid.UUID
	Name           string
	LocateAt       pgtype.UUID
	FullPath       interface{}
	IsDeleted      *bool
	CreatedAt      pgtype.Timestamptz
	LastModifiedAt pgtype.Timestamptz
	UserID         uuid.UUID
}

type User struct {
	ID             uuid.UUID
	Email          string
	Password       string
	Name           string
	AvatarUrl      *string
	CreatedAt      pgtype.Timestamptz
	LastModifiedAt pgtype.Timestamptz
}
