// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package db

import (
	"time"

	"github.com/google/uuid"
)

type File struct {
	ID             uuid.UUID `json:"id"`
	Name           string    `json:"name"`
	Url            string    `json:"url"`
	CreatedAt      time.Time `json:"createdAt"`
	LastModifiedAt time.Time `json:"lastModifiedAt"`
	UserID         uuid.UUID `json:"userId"`
	LocateAt       uuid.UUID `json:"locateAt"`
	Description    *string   `json:"description"`
}

type Folder struct {
	ID             uuid.UUID `json:"id"`
	Name           string    `json:"name"`
	LocateAt       uuid.UUID `json:"locateAt"`
	FullPath       []Path    `json:"fullPath"`
	Depth          int32     `json:"depth"`
	IsDeleted      bool      `json:"isDeleted"`
	CreatedAt      time.Time `json:"createdAt"`
	LastModifiedAt time.Time `json:"lastModifiedAt"`
	UserID         uuid.UUID `json:"userId"`
}

type User struct {
	ID             uuid.UUID `json:"id"`
	Email          string    `json:"email"`
	Password       string    `json:"password"`
	Name           *string   `json:"name"`
	AvatarUrl      *string   `json:"avatarUrl"`
	CreatedAt      time.Time `json:"createdAt"`
	LastModifiedAt time.Time `json:"lastModifiedAt"`
	IsValidate     bool      `json:"isValidate"`
}
