export enum User_CRUD_STATUS {
  SUCCESS,
  UNKNOWN_ERROR,
  EMAIL_DUPLICATED,
  INVALID_BODY_FORMAT,
  INVALID_EAMIL_FORMAT
}

export enum Auth_STATUS {
  NOT_AUTHORIZED,
  OUT_DATED,
  AUTHORIZED,
  UNKNOWN_ERROR
}

export enum Folder_CRUD_STATUS {
  SUCCESS,
  UNKNOWN_ERROR,
  FOLDER_DUPLICATED,
  FOLDER_NAME_TOOLONG,
  INVALID_BODY_FORMAT,
  INVALID_FOLDER_FORMAT,
  FOLDER_ID_DUPLICATED
}

export enum File_CRUD_STATUS {
  FILE_NAME_DUPLICATED,
  FAILED,
  SUCCESS,
  FILE_ID_DUPLICATED
}
