export enum User_CRUD_STATUS {
  SUCCESS,
  UNKNOWN_ERROR,
  EMAIL_DUPLICATED,
  INVALID_BODY_FORMAT,
  INVALID_EAMIL_FORMAT
}

export enum Auth_STATUS {
  NOT_AUTHORIZED,
  OUT_DATED,
  AUTHORIZED,
  UNKNOWN_ERROR
}
